# Generated by Django 5.0.2 on 2024-02-17 19:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='message_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4096, verbose_name='История промптов'), default=[], size=None, verbose_name='История промптов'),
        ),
    ]
