# Generated by Django 5.0.2 on 2024-02-17 20:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_telegramuser_message_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='message_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(verbose_name='История промптов'), blank=True, default=list, size=None, verbose_name='История промптов'),
        ),
    ]
